name: AIML1_Docker

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - uses: actions/checkout@v4

    # Step 2: Log in to DockerHub using GitHub secrets
    - name: Log in to Docker Hub
      run: echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

    # Step 3: Build the Docker image
    - name: Build the Docker image
      id: build_image
      run: |
        IMAGE_TAG=$(date +%s)
        docker build . --file Dockerfile --tag aiml1_docker/my-image-name:$IMAGE_TAG
        echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

    # Step 4: Tag the image with 'latest' or any other custom version tag
    - name: Tag the Docker image
      run: docker tag aiml1_docker/my-image-name:${{ env.IMAGE_TAG }} aiml1_docker/my-image-name:latest

    # Step 5: Push the Docker image to DockerHub
    - name: Push Docker image to DockerHub
      run: |
        docker push aiml1_docker/my-image-name:${{ env.IMAGE_TAG }}
        docker push aiml1_docker/my-image-name:latest
